name: venv
channels:
  - default
dependencies:
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pytorch
  - scikit-learn
  - plotly
  - python=3.9
  - notebook
  - torchvision
  - pip
  - pillow
  - tensorflow
  