trigger:
  branches:
    include:
      - master

stages:

  # Preprocess Dataset
  - stage: PreprocessDatasetStage
    jobs:

      - job: PreprocessDataJob
        displayName: Download and proccess datasets
        steps:

          - task: UsePythonVersion@0
            displayName: Install Python Packages
            inputs:
              versionSpec: '3.10'
              addToPath: true
              architecture: 'x64'

          - task: Bash@3
            displayName: Install python packages
            inputs:
              targetType: 'inline'
              script: |
                pip install -r requirements.txt
              workingDirectory: '$(System.DefaultWorkingDirectory)/'

          - task: Bash@3
            displayName: Download Dataset for preprocessing
            inputs:
              targetType: 'inline'
              script: |
                wget https://publicimages0.blob.core.windows.net/datasets/Tabular/modecal_cost/medical_cost.zip
              workingDirectory: '$(System.DefaultWorkingDirectory)/notebooks'

          - task: Bash@3
            displayName: Move dataset into data folder
            inputs:
              targetType: 'inline'
              script: |
                mv medical_cost.zip ../data
              workingDirectory: '$(System.DefaultWorkingDirectory)/notebooks'

          - task: PythonScript@0
            displayName: Extract File
            inputs:
              scriptSource: 'inline'
              script: |
                import zipfile
                data=zipfile.ZipFile("../data/medical_cost.zip")
                data.extractall("../data/")
                data.close()
              workingDirectory: '$(System.DefaultWorkingDirectory)/notebooks'

      - job: RunTestOnModule
        dependsOn: 
          - PreprocessDataJob
        steps:
          - task: Bash@3
            continueOnError: false
            displayName: Test Model
            inputs:
              targetType: 'inline'
              script: |
                pip install pytest
                pytest -v -s
              workingDirectory: '$(System.DefaultWorkingDirectory)/model'
      
      # - job: TestModel

  # Deploy Cloud Infrastructure
  # - stage: InfrastructureDeployment
  #   jobs:
  #     - job: DeployResources
      
  # Deploy Model to cloud
  # - stage: DeployApi