trigger:
  branches:
    include:
      - master

stages:

  # Train, validate and test module
  - stage: TrainAndValidateModel
    jobs:

      - job: PreprocessDataAndTrainModel
        displayName: Download and proccess datasets
        steps:

          - task: UsePythonVersion@0
            displayName: Install Python Packages
            inputs:
              versionSpec: '3.10'
              addToPath: true
              architecture: 'x64'

          - task: Bash@3
            displayName: Install python packages
            inputs:
              targetType: 'inline'
              script: |
                pip install -r requirements.txt
              workingDirectory: '$(System.DefaultWorkingDirectory)/'

          - task: Bash@3
            displayName: Download Dataset for preprocessing
            inputs:
              targetType: 'inline'
              script: |
                wget https://publicimages0.blob.core.windows.net/datasets/Tabular/modecal_cost/medical_cost.zip
                mv medical_cost.zip ../data
              workingDirectory: '$(System.DefaultWorkingDirectory)/notebooks'

          - task: Bash@3
            displayName: Train model
            inputs:
              targetType: 'inline'
              script: |
                python train.py
              workingDirectory: '$(System.DefaultWorkingDirectory)/model'

      # - job: TestModel

  # Deploy Cloud Infrastructure
  # - stage: InfrastructureDeployment
  #   jobs:
  #     - job: DeployResources
      
  # Deploy Model to cloud
  # - stage: DeployApi