name: venv
channels:
  - default
dependencies:
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - python=3.9
  - notebook
  - scikit-learn
  - pip
  - pip:
    - gunicorn==20.1.0
    - azure-storage-blob
    - fastapi[all]==0.70.1
    - azure-identity==1.7.0
    - uvicorn[standard]==0.15.0
